### ISSUE TITLE
[BUG] DOMException when clicking the increment button

### ISSUE THREAD

**Issue by ClaudeGontier** [Randy-l7/HoneyMaker#1]
### Bug description
When invoking the `Game.onMouseDown()` method, either manually in the javascript console or by clicking the green increment button, the console trows this error:
`Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.`

### Additional information
Tested on Arch Linux (Firefox 133.0.3-2)
I have uBlockOrigin, tried to disable it without success
I also tried to add the website to the Enhanced Tracking Protection exceptions, again without success

**Comment by ClaudeGontier** [comment]
Hi,
I just tried to reproduce the bug on Chromium 131.0.6778.139-1, and I get a somewhat similar error message:
`Uncaught (in promise) AbortError: The play() request was interrupted because the media was removed from the document.`
The error also links to this documentation: https://goo.gl/LdLk22
Maybe the js code doesn't comply with the way described in this link ?

**Comment by Randy-l7** [comment]
After some debugging, I found out that the issue was caused by the media resource being aborted before it finished loading. I fixed it by properly handling the promises and checking the ready state of the media element before calling play()
